[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"

[[services]]
name = "web"
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "tuya-monitor"
startCommand = "npm run monitor"
restartPolicyType = "ALWAYS"
restartPolicyMaxRetries = 10
